const companyData = [
  {
    "key": 1,
    "Company": "Academic Solutions AB",
    "AboutCompany": "Academic Solutions connect companies/organizations with students. We supply companies with students who are looking for internships, part-time jobs, are going to write their thesis or any other type of assignments linked to the years the students are studying. AcademicSolutions improves the contact between academia and industry by offering a service that can be tailored to suit special needs.",
    "OfficeLocation": "Lund",
    "Number of employees": 3,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis",
    "Name of contact person": "Anna Tunberg",
    "Email of contact person": "anna@academicsolutions.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/AcademicSolution.png")
  },
  {
    "key": 2,
    "Company": "Academic Work",
    "AboutCompany": "Academic Work är Home of the Young Professionals. Vi arbetar med personaluthyrning och rekrytering av akademiker i början av sina karriärer, antingen när de studerar eller upp till fem år efter examen. Det är vår nisch, vårt expertområde och en målgrupp vi tror på. Academic Work finns i sex länder och förmedlar över 16 000 jobb per år. Genom oss kan du få utvecklande och meriterande deltidsjobb, heltidsarbeten, sommarjobb, internship och talangprogram, knyta viktiga kontakter inför framtiden och få en bra start på din karriär.  \nHos oss påbörjar Young Professionals sina karriärer varje dag, varför gör du inte samma sak?",
    "OfficeLocation": "Kontor i hela Sverige från Malmö till Umeå - totalt 16 kontor i hela Sverige",
    "Number of employees": 850,
    "SustainabilityWork": "•\tVi använder enbart grön el på våra kontor och har rörelsesensorer som styr belysningen.\n•\tVi har en obligatorisk miljöutbildning om året för alla medarbetare.\n•\tVi är certifierade enligt ISO 14001. Det håller oss i framkant och hjälper oss att ständigt förbättra hur vi jobbar.",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Extra job, Full Time Employment",
    "Name of contact person": "My Jensen",
    "Email of contact person": "my.jensen@academicwork.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/AcademicWork.png")
  },
  {
    "key": 3,
    "Company": "Acando",
    "AboutCompany": "At Acando we are all about talent. About talent aggregation and acceleration. We give transformational power to our clients and to our employees. We bring long term value to the world around us by growing the available talent pool for all to tap into. Acando offers one of the best and most popular Trainee Programs on the market! We are always thrilled to get to know potential future colleagues. Come and have a chat with us at the fair!",
    "OfficeLocation": "Malmö, Göteborg, Stockholm, Västerås and Oslo",
    "Number of employees": "1200 employees in Sweden and 2100 globally",
    "SustainabilityWork": "Acando is, starting 2019, reporting triple bottom line! In other words, we are being evaluated not only by profit to our shareholders but also on our impact on society and on the planet as a whole. Acando has since long been strongly committed to economic and social sustainability, and has last year been working more intensely to develop our service offerings regarding environmental impact. We recently incorporated the UN sustainability areas into our business and are also part of an industry initiative to drive environmental action being handed over to the Swedish government this spring. In other words, Acando strives for a more capable world, in all aspects!",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Full Time Employment",
    "Name of contact person": "Sanna Rosell",
    "Email of contact person": "sanna.rosell@acando.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Acando.png")
  },
  {
    "key": 4,
    "Company": "Accenture A/S",
    "AboutCompany": "•\tAccenture is a leading global professional services company, providing a broad range of services and solutions in strategy, consulting, digital, technology, security and operations. Combining unmatched experience and specialized skills across more than 40 industries and all business functions – underpinned by the world’s largest delivery network – we work at the intersection of business and technology to help clients improve their performance and create sustainable value for their stakeholders. With more than 469,000 people serving clients in more than 120 countries, Accenture drives innovation to improve the way the world works and lives.",
    "OfficeLocation": "Stockholm, Copenhagen, Oslo, Malmö, Göteborg",
    "Number of employees": "In Sweden 1300, global 469.000",
    "SustainabilityWork": "From gender equality and climate action to decent work and economic growth and quality education, we are committed to addressing the United Nations’ Global Goals and contributing to the new sustainable development agenda.",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Extra job, Full Time Employment",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Accenture.png")
  },
  {
    "key": 5,
    "Company": "Acconeer",
    "AboutCompany": "Based on research from Lund University, Acconeer has created a unique radar solution that creates new opportunities for human interaction with technology. The radar sensor is based on pulsed coherent radar technology and combines extremely low power consumption with high accuracy. The unique characteristics of this radar sensor make it possible to identify materials and detect motion in advanced sensor applications. The small size, only 5x5 mm, and low power consumption are ideal for IoT. \nAcconeer is located at Ideon Gateway. We are a group of around 40 people, working close together in an agile manner, determined to create a major breakthrough in sensor technology.",
    "OfficeLocation": "Lund",
    "Number of employees": 40,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Full Time Employment",
    "Name of contact person": "",
    "Email of contact person": "info@acconeer.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Acconeer.png")
  },
  {
    "key": 6,
    "Company": "Advenica AB",
    "AboutCompany": "Advenica tillhandahåller expertis, hög assurans och cybersäkerhetslösningar i världsklass för kritisk data-in-motion upp till Top Secret-klassning. Med oss stärker länder,myndigheter och företag informationssäkerheten och digitaliserar ansvarsfullt. Bolaget grundades 1993 och har EU-godkännande på högsta säkerhetsnivå. Våra unika produkter designas, utvecklas och tillverkas i Sverige.",
    "OfficeLocation": "Malmö, Stockholm, Helsinki, Vienna",
    "Number of employees": 55,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Full Time Employment",
    "Name of contact person": "Lars Nagy",
    "Email of contact person": "lars.nagy@advenica.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/advencia.png")
  },
  {
    "key": 7,
    "Company": "ÅF",
    "AboutCompany": "ÅF is an engineering and design company within the fields of energy, industry, infrastructure and digital solutions. We create sustainable solutions for the next generation through talented people and technology. We are based in Europe and our business and clients are found all over the world.",
    "OfficeLocation": "Stockholm, Göteborg, Malmö och drygt ytterligare 80 kontor i Sverige",
    "Number of employees": "10 000",
    "SustainabilityWork": "ÅF Green Day conference brings business leaders, government representatives and civil society together to show how the private sector is taking action and partnering with different sectors of society to advance sustainability priorities and drive social progress",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis, Full Time Employment",
    "Name of contact person": "Anna Grane",
    "Email of contact person": "anna.grane@afconsult.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/AF.jpg")
  },
  {
    "key": 8,
    "Company": "Airthings",
    "AboutCompany": "Airthings is an IoT company creating radon and indoor air quality detectors for consumers and professionals. We are headquartered in the heart of Oslo with offices in both Chicago and Quebec and customers in more than 50 countries. At our headquarters, we develop everything from hardware and firmware to mobile apps, cloud services and a dashboard where we visualize the users data. Airthings was recently named one of the fastest growing companies in Europe by the Financial Times.",
    "OfficeLocation": "Oslo, Chicago, Quebec",
    "Number of employees": 45,
    "SustainabilityWork": "Sustainability is important when creating our products. We no longer use pollutive glue or plastic in our packaging, which is 100% recyclable. We continuously work toward more energy efficiency, and our products allow users to optimize their energy efficiency by tracking and reporting on ventilation",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Full time job after ended studies, apply at http://airthings.com/careers",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Airthings.png")
  },
  {
    "key": 9,
    "Company": "Alten Sverige AB",
    "AboutCompany": "At ALTEN Sweden we develop and deliver expertise for world-leading companies and have a committed team of engineers and IT consultants. Our customers are found in the Energy, Telecom, Automotive, Life Science, Pharmaceuticals, Defence & Aerospace and other industries and we cover the whole product development cycle. We are a part of the Alten Group and have a workforce of over 28.000 in 20 countries.\n\nWe believe that genuine commitment comes through freedom of choice and the opportunity to have a say in one's own professional development. Our business model offers that opportunity. This freedom of choice enables us to offer our customers the very best consultants, regardless of assignment.",
    "OfficeLocation": "Lund, Göteborg, Stockholm, Linköping, Västerås, Jönköping, Örebro, Umeå, Skellefteå och Luleå",
    "Number of employees": "Almost 2.000 in Sweden and global 28.000",
    "SustainabilityWork": "Last year we initiated an energy audit across the entire company with focus on transport and travel related activities, which has given us valuable insight that has been used to create and implement a new travel policy. We will continue with the energy audit and this year will be focusing on our office spaces. \n\n\nOne of our main focus areas is to provide our employees the opportunity to work with something they are passionate about and for a lot of them it is making the world a better place. We offer assignments where they can work with electric cars, climate-smart packaging, or life-saving health care products among other great assignments",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Full Time Employment",
    "Name of contact person": "Mathilda Green",
    "Email of contact person": "mathilda.green@alten.se",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/alten.png")
  },
  {
    "key": 10,
    "Company": "Arm",
    "AboutCompany": "Arm is the world’s leading designer of key technologies that are\nused in semiconductor computer chips. We design the processors\nused in 95% of the world’s smartphones sold each year; and our\ntechnology can also be found in many other devices from digital\nTVs to automotive systems to smart sensors and to the data\ncenters that run the cloud. Our technology is everywhere.\nArm was acquired by SoftBank Group Corp. (SBG) in September\n2016, and is now a fully owned subsidiary of SBG. Arm’s\noperations are independent from the rest of SBG, although Arm\nnow works closely with other SBG companies. Arm also provides\ninsight into technologies used by SBG.",
    "OfficeLocation": "Lund, Budapest, Trondheim, Oulu, Cambridge,",
    "Number of employees": "7500 global",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Full Time Employment",
    "Name of contact person": "Katie Daines",
    "Email of contact person": "katie.daines@arm.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Teknikfokus.png")
  },
  {
    "key": 11,
    "Company": "Auranest",
    "AboutCompany": "Auranest was founded 5 years ago to simplify job hunting by letting users easily synchronize their professional profile to many different job listings sites. Today Auranest is one of the most highly acclaimed companies on the JobTech scene, not only focusing on job seekers but as well to be the infrastructure of other JobTech companies. With a growing customer and partner list Auranest is in a unique position to truly create a great tool for job seekers.",
    "OfficeLocation": "Lund, Stockholm",
    "Number of employees": 12,
    "SustainabilityWork": "We empower the individuals to find their dream job by putting job seekers need in center.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Full Time Employment",
    "Name of contact person": "Babak Vahidi",
    "Email of contact person": "babak@auranest.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/auranest.png")
  },
  {
    "key": 12,
    "Company": "Axis Communications",
    "AboutCompany": "Axis is the market leader in network video. Several of our successful innovations were initiated by students collaborating with us. We offer a number of student opportunities, such as thesis, summer and part time jobs. We don’t make up problems for you to solve – we give you real ones that can have a huge impact on our future groundbreaking products. Each year we recruit many new graduates straight from school. Together we innovate for a smarter, safer world increasing the security of millions of people worldwide. Come join us!",
    "OfficeLocation": "Lund and Linköping in Sweden. Globally 50+ countries.",
    "Number of employees": "In Sweden over 1800 and globally over 1200.",
    "SustainabilityWork": "Sustainability is an integral part of Axis’ long term strategy. With a specific focus on business conduct, social and environmental responsibility, we seek to minimize impacts, create a healthy working environment, eradicate corruption and ensure respect for human rights.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "Emmy Lagergren",
    "Email of contact person": "emmy.lagergren@axis.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Axis.png")
  },
  {
    "key": 13,
    "Company": "Bosch",
    "AboutCompany": "The Lund office is a development site working on software solutions for connecting Bosch devices to the internet in a secure way. Main focus is automotive devices to connect vehicles, but also on CE-devices like the next generation eBike-computer.",
    "OfficeLocation": "Lund",
    "Number of employees": 250,
    "SustainabilityWork": "Environment, society, sustainable innovation, climate-friendly production",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis",
    "Name of contact person": "",
    "Email of contact person": "?",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Teknikfokus.png")
  },
  {
    "key": 14,
    "Company": "Capgemini",
    "AboutCompany": "Capgemini is a world leading IT & Management Consultancy. We have some of the largest companies in the world as our clients and are located in all major cities in Sweden. We are interested in finding students that are interested in Technology and want to be a part of our graduate program. Ignite your career by applying to Capgemini.",
    "OfficeLocation": "All major cities in Sweden",
    "Number of employees": "200 000 +",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Full Time Employment",
    "Name of contact person": "Moa Tollstam",
    "Email of contact person": "moa.tollstam@capgemini.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Teknikfokus.png")
  },
  {
    "key": 15,
    "Company": "CellaVision",
    "AboutCompany": "At CellaVision we work with state-of-the-art methods in image analysis, artificial intelligence and automated microscopy. We´re an innovative, global medical technology company that develop its own leading systems for routine analysis of blood and other body fluids in healthcare services. Our products rationalize manual laboratory work, and secure and support effective workflows and skills development within and between hospitals. While our analyzers are used in labs all over the world, all innovation & engineering takes place at CellaVision headquarters in Lund. Join our business and take part in leading technical development that creates value in the healthcare services!",
    "OfficeLocation": "Lund",
    "Number of employees": 117,
    "SustainabilityWork": "Responsible entrepreneurship is a matter of course for CellaVision. Based on clear guidelines, codes of conduct and objectives, the company is working to reduce its environmental impact, have high business ethics and contribute to a sustainable society.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "Jaqueline Johansson Salonen",
    "Email of contact person": "jasa@cellavision.se",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/CellaVision.png")
  },
  {
    "key": 16,
    "Company": "Combain",
    "AboutCompany": "Combain is providing cloud-services for connected devices. We provides solutions for indoor and outdoor tracking of IoT devices, targets and personnel. Accurate indoor positioning requires machine learning and deep learning algorithms. Apps and cloud-services requires full stack web developers.",
    "OfficeLocation": "Lund, Palo Alto California",
    "Number of employees": 16,
    "SustainabilityWork": "By accurate indoor and outdoor positioning, people can work in a more safe and efficient way. Energy and other resources are saved if companies can work in a smarter way by utilizing Combain positioning technologies.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "Rikard Windh",
    "Email of contact person": "rikard@combain.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Combian.png")
  },
  {
    "key": 17,
    "Company": "Consid AB",
    "AboutCompany": "We are one of Sweden's fastest growing companies which provides consulting services within IT, management and digital marketing. Our mission is to ensure that our clients becomes the best in the world at what they do by taking advantage of the digital world possibilities. We do it with technology that enabled that dictatorships fall, societies change and human development - with Swedish heart and global ambitions.\n\n \n\nOur mission is to ensure that our customers becomes the best in the world at what they do by taking advantage of the digital world's possibilities. We want to help our customers to become better, more efficient and more successful. With the help of the digital world's opportunities that continues to expand at an increasing pace, this is possible. And to ensure our customers get better, more efficient and more successful with our help - it's our favourite thing to do.\n\nConsid has offices in 17 locations in Sweden and we are just over 700 ”Considare”. Our offices in Skåne are located in Malmö and Helsingborg.\n\nYou can check out our vacancies and read more about us by visiting our website www.consid.se",
    "OfficeLocation": "Malmö, Göteborg, Helsingborg, Stockholm, Karlshamn, Karlskrona, Västerås, Örebro, Värnamo, Växjö, Jönköping, Ljungby, Sundsvall, Norrköping, Linköping, Uppsala",
    "Number of employees": "Cirka 700 anställda",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Master thesis, Full Time Employment",
    "Name of contact person": "Jenny Franzén",
    "Email of contact person": "jenny.franzen@consid.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/consid.png")
  },
  {
    "key": 18,
    "Company": "Cybercom",
    "AboutCompany": "Cybercom is an innovative IT consulting company with 20 years of experience in IT and communications technology. Our consultants enable businesses and organisations to benefit from the opportunities of the connected world, to enhance their competitiveness or to achieve efficiency gains. Cybercom’s expertise spans the entire ecosystem of this communication – Connectivity – and our delivery is both local and global.",
    "OfficeLocation": "Several sites in Sweden, Denmark, Finland and Polen.",
    "Number of employees": 1300,
    "SustainabilityWork": "We take responsibly in all countries and in all contexts in which the Group is active. To grow with continued profitability, it is important to take responsibility for how people and the environment are affected by the company’s activities. We therefore work with long-term sustainability issues.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis",
    "Name of contact person": "Sanna Lindberg",
    "Email of contact person": "sanna.lindberg@cybercom.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/CybercomG.png")
  },
  {
    "key": 19,
    "Company": "Danske Bank",
    "AboutCompany": "Danske Bank is the largest bank in Denmark (founded 1871) and one of the leading financial enterprises in northern Europe. The Markets IT team is responsible for building, integrating and supporting our next generation of trading applications. \nWe support asset classes across our investment banking business, including Fixed Income, Equities and Foreign Exchange. \nWe are a high-performance team delivering Danske Bank's global competitive edge with innovative digital solutions.",
    "OfficeLocation": "IT development in Copenhagen, Århus, Vilnius, Bangalore",
    "Number of employees": "3.300 in IT , 20.000 overall",
    "SustainabilityWork": "Our ambition is to drive sustainable progress and positive impact in the societies we are part of. Our Societal Impact Strategy sets the course for our ambition and our related policies, position statements and guide our approach to conducting our business in a sustainable and responsible manner.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/DanskeBank.png")
  },
  {
    "key": 20,
    "Company": "Dirac Research AB",
    "AboutCompany": "Dirac specializes in digital sound optimization solutions with the mission to invent the future of sound. Whether you’re listening to music in your car or home, relaxing with headphones or using your mobile device as a makeshift boombox, audio quality can make or break the experience. Our digital audio solutions fundamentally improve sound quality across all devices for a pristine, dynamic and immersive listening experience.",
    "OfficeLocation": "Uppsala, Copenhagen and China",
    "Number of employees": 80,
    "SustainabilityWork": "We believe that next level signal processing is not about the hardware but the software that will make the difference. Keeping everything on a software basis dramatically decreases the need to update hardware, for us and our costumers. Sustainability and digital signal processing goes hand in hand.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis, Full Time Employment, Internship",
    "Name of contact person": "Poya Ataei",
    "Email of contact person": "poya.ataei@dirac.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/DiracResearch.png")
  },
  {
    "key": 21,
    "Company": "Ericsson",
    "AboutCompany": "Ericsson is one of the leading providers of Information and Communication Technology (ICT) to service providers, with about 40% of the world’s mobile traffic carried through our networks. We enable the full value of connectivity by creating game-changing technology and services that are easy to use, adopt and scale, making our customers successful in a fully connected world. For more than 140 years, our ideas, technology and people have changed the world: real turning points that have transformed lives, industries and society as a whole.\n\nWant to know more? Come by us and let us tell you how you can make a difference.",
    "OfficeLocation": "Stockholm, Lund, Gothenburg, Linköping, Båstad, Karlskrona, Luleå",
    "Number of employees": "Sweden: 14000, Globally: 100 000",
    "SustainabilityWork": "Sustainability shapes what we do.  We have always driven\nour technology development with the intention to improve people’s lives and \ncontribute to the betterment of society - from within and outwards.  \n\nRead more: www.ericsson.com/en/about-us/sustainability-and-corporate-responsibility",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Full time positions",
    "Name of contact person": "Lisa Boberg",
    "Email of contact person": "lisa.boberg@ericsson.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/ericsson.png")
  },
  {
    "key": 22,
    "Company": "Grade AB",
    "AboutCompany": "Grade – Creating Employee Engagement\n \nAt Grade in Lund, we have since 1995 been developing one of the Nordics leading employee engagement software products.\n\nOur software not only measures the amount of employee engagement within companies and organizations, it also provides a great deal of solutions and counter measures, for dealing with these issues.\n\nThrough our user-friendly software, the user can manage employee’s personal development, digital learning, feedback, appraisals, goals, competence and career paths.",
    "OfficeLocation": "Lund and Stockholm",
    "Number of employees": 30,
    "SustainabilityWork": "We are all making an imprint on our planet and we need to reconsider the way we treat it. Therefor we but a lot of pride in recycling and downsizing air-travel by meeting online. We compensate by paying for carbon offsets. We not only pay for them once, we actually pay double.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Master thesis, Full Time Employment",
    "Name of contact person": "Rickard Nygren",
    "Email of contact person": "rickard.nygren@grade.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Grade.png")
  },
  {
    "key": 23,
    "Company": "HemoCue AB",
    "AboutCompany": "HemoCue is a global leader in a field of diagnostics known as near patient, or point-of-care, testing. In 1982, HemoCue AB, based in Ängelholm, Sweden, introduced the first system making accurate hemoglobin testing possible in near-patient settings. Since then, more than 400,000 HemoCue systems have been sold worldwide. The company also offers point-of-care tests for glucose, urine albumin, HbA1c, total and differential white blood cell count. HemoCue subsidiaries, franchises, and third-party distributors generate revenue in more than 130 countries worldwide. Since April 2013 HemoCue is part of the Radiometer Group. Additional company information is available at hemocue.com.",
    "OfficeLocation": "Ängelholm",
    "Number of employees": "260 in Sweden and 400 global",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Full Time Employment",
    "Name of contact person": "Christina Jonéus",
    "Email of contact person": "cjo@hmocue.se",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/hemocue.png")
  },
  {
    "key": 24,
    "Company": "HMS",
    "AboutCompany": "In a world where all devices are intelligent and networked, HMS is the leader in making industrial devices and systems communicate - for a more productive and sustainable world.",
    "OfficeLocation": "Halmstad, Göteborg",
    "Number of employees": "In Sweden 230 and Global 600",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "Louise Odin",
    "Email of contact person": "Loo@hms.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/hms.png")
  },
  {
    "key": 25,
    "Company": "InfraSight Labs",
    "AboutCompany": "InfraSight Labs utvecklar och säljer vScope - automatisk IT-inventering för alla inom IT som är i behov av uppdaterad information i ett enkelt format.\n\nvScope samlar information om IT, oavsett om den finns lokalt, i molnet eller outsourcat. Med vScope kan vem som helst skapa kraftfulla rapporter, analyser och statistik som kan användas för att säkerställa en säker, stabil och kostnadseffektiv leverans av IT. \n\nVi är ständigt på jakt efter nyfikna och drivna medarbetare som vill vara med på vår resa som entreprenörsdrivet bolag som vill ta världen! Ska du med?",
    "OfficeLocation": "Malmö",
    "Number of employees": 11,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Extra job, Master thesis, Full-time employment",
    "Name of contact person": "",
    "Email of contact person": "?",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/InfraSightLabs.png")
  },
  {
    "key": 26,
    "Company": "Ingenjörer utan gränser",
    "AboutCompany": "Ingenjörer utan gränser är en ideell nationell organisation med syftet att använda sin ingenjörskonst för att skapa en bättre framtid. Organisationen består av ett stort antal lokalgrupper som drivs av yrkesverksamma och studenter.\nLokalgruppen i Lund är en studentorganisation med huvudmålet att föra samman studenter, universitet och näringsliv till ett gemensamt forum som bidrar till kunskapsutbyte och uppmärksammar utmaningarna inom hållbarhet och global utveckling. Vi består av åtta utskott som samordnas av en ledningsgrupp.",
    "OfficeLocation": "Malmö, Lund, Stockholm, Uppsala, Linköping, Luleå",
    "Number of employees": 300,
    "SustainabilityWork": "Vi bidrar till en mer hållbar värld genom att etablera långsiktiga infrastrukturlösningar i delar av världen där infrastrukturen är mycket dålig eller saknas helt. Sjukhus, solcellpaneler och vattentankar är exempel på sådant som ingår i våra projekt.",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Voluntary work",
    "Name of contact person": "EWB Lund",
    "Email of contact person": "lund@ewb-swe.org",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/IngenjorerUtanGranser.jpg")
  },
  {
    "key": 27,
    "Company": "Jayway",
    "AboutCompany": "We combine creativity and technology to swiftly transform ideas into realities on mobile, web and in the cloud",
    "OfficeLocation": "Malmö, Halmstad, Stockholm, Köpenhamn, San Francisco",
    "Number of employees": "250 in total",
    "SustainabilityWork": "Don’t waste food - In the Malmö office there is a No Food Waste button. When there are leftovers from an events, the food is placed on the table, you press the button and immediately a picture is sent out on Slack telling about the extra food in the kitchen.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Master thesis, Full Time Employment",
    "Name of contact person": "Studio leads",
    "Email of contact person": "careers@jayway.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Jayway.png")
  },
  {
    "key": 28,
    "Company": "Knightec AB",
    "AboutCompany": "Knightec is a consultancy specialising in technology, quality and project management for product development, systems and production. Among our customers you find many of Sweden's largest industrial companies within automotive, Life science, security, packaging and industry. \n\nKnightec creates a better future via development of people and technology, driven by the belief that a diversified team is the key to success. Right now Knightec consists of more than 30 nationalities and a third of our employees are women. Knightec's ambition is to further increase this diversity. We believe in daring to be the best, exceeding expectations and showing consideration for colleagues and customers.",
    "OfficeLocation": "Göteborg, Helsingborg, Linköping, Lund, Stockholm, Umeå, Uppsala, Västerås and Örnsköldsvik",
    "Number of employees": "Around 600 in Sweden",
    "SustainabilityWork": "Knightec inspire students in schools like Kryddgårdsskolan in Malmö to pursue a career in tech. And have a management with a New Year resolution to only eat vegetarian. Call us crazy but our employees rank us as the third best employer in Sweden. One reason is because Knightec act for the future",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Full Time Employment",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/KNIGHTEC.jpg")
  },
  {
    "key": 29,
    "Company": "Knowit",
    "AboutCompany": "We create a sustainable and humane society through digitization and innovation.\nBy combining strategic capacity with a passion for technology and creative solutions, we create digital opportunities and long-term value.\nOur core values\nWe are decent\nWe are close and available\nWe are passionate about innovation\nKnowit is a consultancy firm that creates unique customer values by offering digital and cross-functional solutions from three business areas: Experience, Insight and Solutions. What sets us apart is our ability to combine expertise in design and communication, management consulting and IT. Knowit has around 2,000 employees.",
    "OfficeLocation": "Malmö, Göteborg, Stockholm, Karlstad, Jönköping, Gävle, Linköping, Luleå, Sundsvall, Uppsala, Örebro, Borlänge,Oslo, Helsingfors, Köpenhamn, Bremen, Arendal, Bergen, Kristiansand, Stavanger, Trondheim",
    "Number of employees": 2000,
    "SustainabilityWork": "Creating long-term value by integrating environmental, social, and financial risks and opportunities in business strategy and operations. Integrating sustainability contributes to creating an attractive and flexible company that is equipped for a changeable business landscape.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Extra job, Master thesis",
    "Name of contact person": "",
    "Email of contact person": "?",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/knowit.png")
  },
  {
    "key": 30,
    "Company": "Lime",
    "AboutCompany": "At Lime, we love CRM! \n\nSince the beginning we have helped more than 6000 companies to reach better results with the help of easy-to-use CRM solutions that we develop, consult and support ourselves. Today we are over 220 colleagues and one of the largest CRM suppliers in the Nordic countries. We are extremely passionate, and we usually say that the only thing we take seriously is our customers. Still interested? Great! \n\nWe are constantly on the lookout for new and passionate talents with a strong technical interest. Now we are looking for you who wants to be a part of the Nordics sharpest CRM-team and our Nordic Trainee Program with start in January or August every year!",
    "OfficeLocation": "Lund, Gothenburg, Stockholm, Copenhagen, Oslo, Helsinki.",
    "Number of employees": "In Sweden 195 and global 230.",
    "SustainabilityWork": "- We minimize travel. When we travel we coordinate travels and transportation with minimal impact on the environment. \n- We have a waste management practice that promote reductions and recycling, including re-use.\n- We minimize all paper usage in the office and use electronic storage instead.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis, Full Time Employment, Trainee program",
    "Name of contact person": "Cornelia Olsérius",
    "Email of contact person": "cornelia.olserius@lime.tech",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Lime.png")
  },
  {
    "key": 31,
    "Company": "Lunds tekniska högskola",
    "AboutCompany": "Lunds universitet grundades 1666 och rankas återkommande som ett av världens 100 främsta\nlärosäten. Här finns 42 000 studenter och 7 400 medarbetare i Lund, Helsingborg och Malmö.\nVi förenas i vår strävan att förstå, förklara och förbättra vår värld och människors villkor.\nwww.lth.se\nCivilingenjörsutbildningar på Teknikfokus:\nDatateknik datateknik@kansli.lth.se\nInformations- och kommunikationsteknik infocom@kansli.lth.se\nElektroteknik elektroteknik@kansli.lth.se\nMedicin och Teknik medicinochteknik@kansli.lth.se\nInternationella mastersprogram på Teknikfokus:\nEmbedded Elecronics engineering embeddedee@master.lth.se\nWireless Communications wireless@master.lth.se",
    "OfficeLocation": "Lund, Helsingborg",
    "Number of employees": "LTH har 9 000 studenter och 1 500 anställda från hela världen",
    "SustainabilityWork": "Lunds universitet arbetar för en bättre miljö och en hållbar utveckling genom sina kärnverksamheter – utbildning, forskning och samverkan",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis",
    "Name of contact person": "Roger von Moltzer",
    "Email of contact person": "roger.von_moltzer@lth.lu.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/LTH.png")
  },
  {
    "key": 32,
    "Company": "Lunicore",
    "AboutCompany": "Lunicore är ett av Nordens främsta studentdrivna konsultbolag. Våra konsulter får chansen att utveckla sin kompetens och få kontakt med näringslivet redan innan examen. Våra uppdrag kräver ofta en syntes av skilda kompetenser och vi anställer studenter från hela Lunds Universitet, bland annat studerar våra konsulter industriell ekonomi, data, systemvetenskap och juridik. Efter avslutad anställning är våra konsulter mycket eftertraktade på arbetsmarknaden. Lunicorealumner arbetar numera på företag som Acando, Netlight, McKinsey och Accenture.\n \nKänner du att du är ute efter en ny utmaning men ännu inte tagit examen? Skicka då in din ansökan - vi är alltid intresserade av nya talanger!",
    "OfficeLocation": "Lund",
    "Number of employees": "About 70",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Extra job",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Lunicore.png")
  },
  {
    "key": 33,
    "Company": "Medical Imaging Technologies",
    "AboutCompany": "Founded in 2009 and proudly headquartered in Lund, Sweden, Medical Imaging Technologies provides complete audiovisual integration for hospitals - connecting interventional labs and operating rooms within the hospital and beyond.\nOur image management technology enables medical professionals to record, share and save video, audio and image sources. With more than 100 installations at 40 hospitals across 12 countries, we are an international group of companies operating in India, the Nordics, United Arab Emirates and United Kingdom.",
    "OfficeLocation": "Lund, Sweden. Wakefield, UK. Delhi, India. Dubai, United Arab Emirates.",
    "Number of employees": "About 30, of which half are in Sweden.",
    "SustainabilityWork": "We are certified to ISO-13485, an international standard that focuses on what we do to deliver safe and effective medical devices. We believe that audio-visual integration can help hospitals get remote access to expertise, promote medical training and continuously improve the quality of healthcare.",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Master thesis",
    "Name of contact person": "Anna Wanland",
    "Email of contact person": "anna.wanland@medicinskbildteknik.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/MedicalImagingTech.jpg")
  },
  {
    "key": 34,
    "Company": "Neodev AB",
    "AboutCompany": "Neodev AB is a Swedish consulting firm operating in the Öresund region. Our main expertise is software engineering with business areas: artificial intelligence, web, embedded, mobile applications and test automation. We offer solutions from prototyping to implementation, as well as initial guidance and advise on how you can best use machine learning to make your product more efficient and competitive for the future. For more information, visit www.neodev.se or contact us at info@neodev.se.",
    "OfficeLocation": "Malmö",
    "Number of employees": 20,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "Fredrika Olsson",
    "Email of contact person": "fredrika.olsson@neodev.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Neodev.png")
  },
  {
    "key": 35,
    "Company": "Netcompany",
    "AboutCompany": "Netcompany delivers business critical IT solutions and consultancy. Due to our incomparable track of record, we keep landing prestigious and complex projects, nationally and internationally. Not only does it mean that our growth has been unstoppable for the last decade, we also have the pleasure of managing projects that makes a difference in both the private and public sector. Due to our career model, Netcompany Academy, all employee’s personal career progress is at high focus, and a responsibility we take very serious. At Netcompany we encourage to have fun. We believe that great collegial bands foster great collaborative skills, thus great solutions and results for our customers.",
    "OfficeLocation": "Copenhagen, UK, Vietnam, Poland, Norway",
    "Number of employees": "1800+",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Full Time Employment, Extra job",
    "Name of contact person": "Anne Honum Høy Jørgensen",
    "Email of contact person": "ahhj@netcompany.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Netcompany.png")
  },
  {
    "key": 36,
    "Company": "Netlight Consulting AB",
    "AboutCompany": "Digitalization is about the people. Netlight offers a unique community and career development in an international setting. Our flat organization is characterized by high engagement along with company wide cooperation. As a top-ranked IT and Management consultancy company, we work with some of the most significant companies within the forefront of digitalization, employing more than 1000 people. We have several times received awards as a top employer, as well as for our growth, continued profitability and our engagement for equality within the IT industry.",
    "OfficeLocation": "Stockholm, Oslo, Helsinki, Copenhagen, Munich, Berlin, Hamburg and Zurich",
    "Number of employees": 1200,
    "SustainabilityWork": "We have a train first and a veggie first policy as well as a carbon offset plan. As part of this plan, we've also teamed up with Go Climate Neutral to help fund climate investments in the world. We are also on a plastic diet and in 2018 we made climate investments for all employees' footprints.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Full Time Employment",
    "Name of contact person": "Talent Search Netlight",
    "Email of contact person": "jobs@netlight.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Netlight.png")
  },
  {
    "key": 37,
    "Company": "Norconsult Astando",
    "AboutCompany": "Norconsult Astando är ett kombinerat produkt- och konsultbolag som tar fram IT-lösningar för ett hållbart samhälle. Vi arbetar med att visualisera och bearbeta lägesbunden information på ett intuitivt och tydligt sätt. Våra kunder är därför främst offentlig verksamhet.",
    "OfficeLocation": "Stockholm, Göteborg, Mora, Västervik",
    "Number of employees": 32,
    "SustainabilityWork": "Något vi vill ska genomsyra vår verksamhet och är därför ett av våra strategi-ben.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "Carina Palmqvist",
    "Email of contact person": "carina.palmqvist@norconsult.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/NoISAstando.png")
  },
  {
    "key": 38,
    "Company": "Nordea",
    "AboutCompany": "Nordea is the largest financial services group in Northern Europe. We count more than 30.000 employees who cooperate to offer our customers the best service and develop new products in response to changes in the market. \nNordea runs one of the largest IT operations in the Nordics. Using cutting edge technologies, we develop high performance innovative systems in close cooperation with business divisions across the Nordic region. \n\nDid you know that Nordea is generally believed to be one of the world’s most technologically advanced banks?",
    "OfficeLocation": "Nordic capitals as well as Gdansk in Poland",
    "Number of employees": 30000,
    "SustainabilityWork": "In Nordea, our business model evolves around ESG, which stands for Environmental, Social and Governance. In a business context, this means that we strive to have our products and services contribute to a sustainable development. You can find more info here: https://www.nordea.com/en/sustainability/",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Full Time Employment, Graduate Program",
    "Name of contact person": "Kirsten Nielsen",
    "Email of contact person": "it.talent@nordea.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Nordea.png")
  },
  {
    "key": 39,
    "Company": "ONE Nordic AB",
    "AboutCompany": "ONE Nordic är en av Sveriges ledande leverantörer av tekniska konsulttjänster, entreprenader och service inom energi- och industrisektorn. \nMed vår rikstäckande organisation och lokala kännedom tar vi ansvar för och levererar högklassiga tjänster och lösningar till energiproducenter, distributörer och energianvändare. Vi har marknadens bästa kompetens för att utveckla, bygga, modernisera, optimera och underhålla kundernas anläggningar. Vi arbetar bland annat med de största aktörerna i branschen och tillsammans utvecklar vi högteknologiska och hållbara energisystem. ONE Nordic har cirka 1000 medarbetare och huvudkontoret ligger i Malmö.",
    "OfficeLocation": "På ca 25 orter i landet",
    "Number of employees": 1000,
    "SustainabilityWork": "",
    "Interested in": "Electrical Engineering",
    "Offer": "Summer job, Full Time Employment, Traineeprogram",
    "Name of contact person": "Anna Fredricson",
    "Email of contact person": "anna.fredricson@one-nordic.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Teknikfokus.png")
  },
  {
    "key": 40,
    "Company": "Qlik",
    "AboutCompany": "Qlik helps enterprises around the world move faster, work smarter, and lead the way forward with an end-to-end solution for getting value out of data. Our platform is the only one on the market that allows for open-ended, curiosity-driven exploration, giving everyone – at any skill level – the ability to make real discoveries that lead to real outcomes and transformative changes. We are a Values-Driven organization, operating over 100 countries with 45,000 customers around the world.",
    "OfficeLocation": "Globally - Lund is for our R&D recruitment",
    "Number of employees": "In Lund 400+",
    "SustainabilityWork": "Please see our website for all our CSR activities",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Master thesis, Full Time Employment, New Grad Programme",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Qlik.jpg")
  },
  {
    "key": 41,
    "Company": "Sentian.ai",
    "AboutCompany": "Sentian.ai is a fast growing AI company offering both products and services. We have big customers, a lot of experience and data. En mycket utvecklande miljö utlovas!",
    "OfficeLocation": "Malmö",
    "Number of employees": 17,
    "SustainabilityWork": "Our products are used to make large companies much more efficient and hence much more sustainable.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Extra job, Master thesis, Jobs",
    "Name of contact person": "",
    "Email of contact person": "?",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/SentianAI.png")
  },
  {
    "key": 42,
    "Company": "Siemens",
    "AboutCompany": "We’re changing the cities you live in, the places you work, the energy that powers your home, and the way the products you love are manufactured.\n\nBy reimagining the world around us, creating solutions to the most challenging problems and making infrastructure more intuitive, we’re improving the lives of people today and for generations to come.",
    "OfficeLocation": "HQ in Stockholm. Main offices in Malmö, Göteborg och Sundsvall",
    "Number of employees": "In Sweden 4000. Globally 360.000",
    "SustainabilityWork": "Siemens goal is to be a carbon neutral by 2030. Focus is on energy-efficiency, decentralized energy systems, intelligent e-mobility solutions, and green electricity purchasing. An example is the eHighway system in Gävleborg, cutting the electricty consumption by half and reducing air pollution.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis",
    "Name of contact person": "Annah Håkansson",
    "Email of contact person": "annah.hakansson@siemens.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Siemens.jpg")
  },
  {
    "key": 43,
    "Company": "Sigma IT Consulting",
    "AboutCompany": "Sigma IT Consulting har idag ca 1 200 medarbetare. Vi drivs av vår vision Expect a Better Tomorrow. \nVi arbetar med tekniska och innovativa IT-lösningar åt våra kunder inom framförallt digitalisering & webb, IoT och AI. Våra erbjudanden omfattar även projektledning, kravhantering, testning, BI och Data Science.\nIndividuella utbildningspaket och certifieringar är några utav våra många förmåner. Vi tror på Work & Life balance! Pingisturneringar, schackspel, ölprovning o andra teamaktiviteter gör att sammanhållningen är på topp! Som kollektivanslutna har vi ett generöst friskvårdsbidrag och belönar oss själva med gemensamma resor och aktiviteter när vi uppnått våra satta mål!",
    "OfficeLocation": "Malmö, Göteborg, Stockholm o runt 20 andra städer i Sverige",
    "Number of employees": "1 200",
    "SustainabilityWork": "We are a supporting member of the UN sustainability initiative called UN Global Compact. As a member, we are committed to stand up for the UN's ten principles of human rights, labor law, the environment, and anti-corruption, and we work to integrate them into our corporate strategy.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Full Time Employment",
    "Name of contact person": "Maria Jaern Ekengren",
    "Email of contact person": "maria.jaern.ekengren@sigma.se",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Sigma.png")
  },
  {
    "key": 44,
    "Company": "Smart Refill",
    "AboutCompany": "Smart Refill develops secure payment and information solutions for the telecom and fintech sectors. Our mobile and web-based services make life a little simpler for the users and helps our customers develop their digital offer.\n\nWe take care of the entire development process from start to finish: building applications, managing operations, and providing maintenance and app updates. Together with the customer, we design tailor-made applications with a short time-to-market thanks to our modular platform of services. And you can always feel safe: we are PCI DSS Level 1 certified and an approved Payment service provider by Finansinspektionen (Swedish Financial Supervisory Authority).",
    "OfficeLocation": "Helsingborg, Taipei, Stockholm",
    "Number of employees": 30,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/SmartRefill.png")
  },
  {
    "key": 45,
    "Company": "Softhouse Consulting",
    "AboutCompany": "We are a consultancy company that is excellent at developing solutions with software and developing people and businesses. We’ve been doing this since 1996. Today we are one of the leading companies in Scandinavia within Lean & Agile. Softhouse is a privately-owned Swedish company, that shown growth and profitability every year.",
    "OfficeLocation": "Malmö, Helsingborg, Växjö, Karlskrona, Jönköping, Stockholm, Sarajevo",
    "Number of employees": 200,
    "SustainabilityWork": "Softhouse develops ticketing and travelling solutions for Public Transportation in the Nordic e.g Skånetrafiken & Flytoget. We try to help Public Transportation in Sweden to reach their goal of double the number of travellers with robust back ends and simple, user friendly and good looking apps.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis, Full Time Employment",
    "Name of contact person": "Ola Persson",
    "Email of contact person": "ola.persson@softhouse.se",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/Softhouse.jpg")
  },
  {
    "key": 46,
    "Company": "Storytel",
    "AboutCompany": "We believe in stories and want to be the obvious choice for all audiobook lovers. Today, we are offering tens of thousands of audiobooks and e-books and more than 700 000 subscribers worldwide use Storytel to inspire and entertain. Storytel is an entrepreneur-driven company and is growing rapidly. We are the market leader for streamed audiobooks in Sweden and our focus is to supply a great experience to our customers and have fun at work! We love what we do!",
    "OfficeLocation": "Lund, Stockholm, Köpenhamn, Umeå",
    "Number of employees": "In Sweden 160, Global 300",
    "SustainabilityWork": "Storytel has a Code of Conduct to guide the employees of Storytel to make decisions that are sustainable for the company and that will sustain the rapid growth of the firm over time. Storytel is aware of its impact on the environment and carefully considers its stakeholders in decision-making.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Master thesis, Full time employment",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Storytel.png")
  },
  {
    "key": 47,
    "Company": "Sveriges Ingenjörer",
    "AboutCompany": "Ditt liv som ingenjör börjar nu\n\nSveriges Ingenjörer välkomnar dig till vårt unika nätverk med 150 000 ingenjörsmedlemmar. Som medlem erbjuder vi dig träning och stöd inför skarpt läge med allt från cv-granskning och karriärcoachning till hjälp med intervjuteknik. Du tar även del av landets bästa lönestatistik, digitaltidningen Ny Teknik samt aktiviteter som hålls på ditt lärosäte. Dessutom har du möjlighet att teckna förmånliga försäkringar och du har tillgång till experthjälp om något skulle gå snett på sommar eller extrajobbet.\n\nVälkommen att börja ditt liv som ingenjör med oss!",
    "OfficeLocation": "Stockholm",
    "Number of employees": 150,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Extra job",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/SverigesIngenjorer.png")
  },
  {
    "key": 48,
    "Company": "Systemite",
    "AboutCompany": "We love system engineering and software development. Working at Systemite means we get to do just that – all day, with an awesome group of people. And since others love what we do too, our need for skilled people is growing. Systemite provides one of the market's most advanced information management platforms for system engineering and software development.\n\nOur product SystemWeaver enables easy integration of company design information for each component and weaves all the information together in one system. SystemWeaver has become an important platform in the automotive industry where we work with customers such as Nevs, Volvo Cars and Volvo Trucks.",
    "OfficeLocation": "Göteborg",
    "Number of employees": 29,
    "SustainabilityWork": "With our product, SystemWeaver, we enable cross-functional teams to work together in tight collaboration, even with team members located in different cities or even countries. This results in reduced travel and therefore in reduced climate impact.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis, Full Time Employment",
    "Name of contact person": "Matilda Boberg",
    "Email of contact person": "matilda.boberg@systemite.se",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/systemite.png")
  },
  {
    "key": 49,
    "Company": "Tactel",
    "AboutCompany": "Tactel is a design and technology agency that develops digital solutions to make life easier for millions of people. We combine our knowledge about end users' needs and their expectations on digital services, with solid knowledge in design and development in order to design services that are easy to work with and familiar to all users.\n\nThrough innovation, smart design and advanced technology, we develop digital services that break new ground. To realize the best innovative solutions with high quality we work together, we are one team, consisting of designers, software developers and testers.",
    "OfficeLocation": "Malmö, Stockholm, Umeå",
    "Number of employees": 90,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Master thesis, Full Time Employment",
    "Name of contact person": "Isabel Holm",
    "Email of contact person": "isabel.holm@tactel.se",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/TACTEL.png")
  },
  {
    "key": 50,
    "Company": "Telavox",
    "AboutCompany": "Telavox consists of 250 curious employees who never fear the challenge of finding new ways. We are an agile IT company with ants in our pants and we have disrupted the telecom industry since 2003 with our great product. We offer a creative environment, a lot of own responsibilities, flexible work hours and the opportunity to grow with us. It is super important for us to laugh a lot while working and we love spending time together. Come and talk to us if you are dedicated to program yourself into the future along with awesome colleagues!",
    "OfficeLocation": "Malmö, Stockholm, Jönköping, Oslo, Helsingfors, Aarhus, London",
    "Number of employees": 250,
    "SustainabilityWork": "Telavox measure and compensate for our CO2 impact x2 and at our events and kick offs, all food are 100% vegetarian. \n\nAt our kick off in January, all our employees got the opportunity to join a environment workshop were we started working on our sustainablity goals and strategy for Telavox.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Master thesis, Full time job after studies",
    "Name of contact person": "Victoria Linden",
    "Email of contact person": "victoria.linden@telavox.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/telavox.png")
  },
  {
    "key": 51,
    "Company": "Tetra Pak",
    "AboutCompany": "Tetra Pak is the world's leading food processing and packaging solutions company. Working closely with our customers and suppliers, we provide safe, innovative and environmentally sound products that each day meet the needs of hundreds of millions of people in more than 160 countries. With more than 24,000 employees around the world, we believe in responsible industry leadership and a sustainable approach to business.  Our motto, “PROTECTS WHAT’S GOOD™,\" reflects our vision to make food safe and available, everywhere.​​",
    "OfficeLocation": "Lund",
    "Number of employees": "In Sweden 3 700 and global 24 800",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Trainee programs",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/TetraPak.png")
  },
  {
    "key": 52,
    "Company": "Tink",
    "AboutCompany": "We are data-driven banking.\n\nTink enables banks and financial institutions to become data-driven through smart, precise, future-proof technology. \n\nFounded in Stockholm in 2012, our partners include Nordea, BNP Paribas Fortis, Klarna, ABN AMRO and SEB. Through our technology, our mission is to help people understand their finances, empower them to make smarter decisions and ultimately bring financial happiness. Tink has raised over 250 million SEK in venture capital and in the past 18 months we have grown from 30 to over 130 people.",
    "OfficeLocation": "Stockholm",
    "Number of employees": 130,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Extra job, Master thesis, Full time employment",
    "Name of contact person": "",
    "Email of contact person": "?",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/tink.png")
  },
  {
    "key": 53,
    "Company": "Trafikverket",
    "AboutCompany": "Sverige är ett stort, avlångt och glest befolkat land. För att allt ska fungera måste vi kunna ta oss till varandra. Det handlar om allt från arbetspendling, släktkalas och matcher som ska spelas, till gods som ska levereras och tomater som ska hamna på tallriken. Här har Trafikverket en avgörande roll. Vi har ansvaret för att underhålla och rusta upp tiotusentals mil av järnväg, vägar och färjeförbindelser. Samtidigt utvecklar vi hela infrastrukturen genom innovativa lösningar som bidrar till att nå både klimatmålen och nollvisionen. Men framför allt ser vi till att korta avstånden mellan människor och företag. Mellan stad och land. Mellan generationer och landsändar.",
    "OfficeLocation": "Hela Sverige",
    "Number of employees": 8000,
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Trainee",
    "Name of contact person": "Fanny Edfeldt",
    "Email of contact person": "Fanny.edfeldt@trafikverket.se",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/Trafikverket.gif")
  },
  {
    "key": 54,
    "Company": "u-blox",
    "AboutCompany": "Swiss-based u-blox (SIX:UBXN) is the global leader in wireless and positioning semiconductors for the automotive, industrial and consumer markets. Our solutions enable people, vehicles and machines to locate their exact position and wirelessly communicate via voice, text or video. With a broad portfolio of chips, modules and software solutions, u-blox is uniquely positioned to allow OEMs to develop innovative solutions that enable mobility quickly and cost-effectively. With headquarters in Thalwil, Switzerland, u-blox is globally present with offices in Europe, Asia and the USA.",
    "OfficeLocation": "Malmö",
    "Number of employees": "In Sweden 60 and global 1100",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Full Time Employment",
    "Name of contact person": "Tina Grönquist",
    "Email of contact person": "tina.gronquist@u-blox.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/ublox.png")
  },
  {
    "key": 55,
    "Company": "Unity Technologies",
    "AboutCompany": "Unity is the creator of the world’s most widely-used real-time 3D (RT3D) development platform, providing content creators around the world with the tools they need to build rich, interactive 2D, 3D, VR and AR experiences. In fact, apps made with Unity reach 2.7 billion devices worldwide, and were installed more than 24 billion times in the last 12 months.",
    "OfficeLocation": "Copenhagen, Stockholm",
    "Number of employees": "250 in Copenhagen, Globally 2000",
    "SustainabilityWork": "",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Extra job, Full Time Employment",
    "Name of contact person": "Jessica Hughes",
    "Email of contact person": "jessicah@unity3d.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/unity.png")
  },
  {
    "key": 56,
    "Company": "Venture Cup",
    "AboutCompany": "Venture Cup have supported tens of thousands of entrepreneurs and helped nearly 15 000 ideas to blossom since the start in 1998. We are Sweden's no. 1 competition and the competition where ideas become businesses. Each year we arrange two competitions, IDEA and STARTUP. The spring is all about startups in an early phase, and during the fall the competition is all about ideas. By challenging yourself, meet our network and get feedback on the business idea, both the entrepreneur and the business idea develops during the competition process.",
    "OfficeLocation": "Lund, Göteborg, Stockholm, Umeå and Luleå",
    "Number of employees": 11,
    "SustainabilityWork": "Venture Cups purpose is to connect people with ideas to experts and the crowd, to ignite the creation of new businesses and empower the growth of Sweden.",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "To compete in our competitions",
    "Name of contact person": "",
    "Email of contact person": "?",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/ventureCup.png")
  },
  {
    "key": 57,
    "Company": "Verisure",
    "AboutCompany": "We are people who protect people.\nEvery day, Verisure does something amazing. By protecting what matters most, we change lives for the better.\nWe protect people beyond expectations, transforming our customers’ lives–and our industry.\nWe do this by building on over 30 years of insights, experience and innovation.\nThe result is peace of mind. It’s a role we are proud to play and will continue to fulfill for generations to come.",
    "OfficeLocation": "Malmö, Linköping, Stockholm and 14 countries across Europe and Latin American.",
    "Number of employees": "A little over 400 people, internationally 16 000.",
    "SustainabilityWork": "Our recycling and refurbishment department receive dysfunctional products and make sure that they are taken care of instead of being thrown out. We refurnish and re-use them as new products to make sure we don’t contribute to unnecessary consumption.",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Extra job, Master thesis, Full Time Employment",
    "Name of contact person": "Mette Schäfer",
    "Email of contact person": "mette.schafer@verisure.com",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/verisure.png")
  },
  {
    "key": 58,
    "Company": "Visma",
    "AboutCompany": "Visma offers software and services that simplify and digitise core business\nprocesses in the private and public sector. The group operates across the entire\nNordic region along with Benelux, Central and Eastern Europe. With over 8,000\nemployees and more than 800,000 customers, Visma is one of Europe’s leading\nsoftware companies. Visit Visma.se/karriar",
    "OfficeLocation": "Stockholm, Göteborg, Malmö, Eskilstuna, Gävle, Halmstad, Helsingborg, Hudiksvall, Jonsered, Kalmar, Karlstad, Kristianstad, Linköping, Lund, Munkedal, Norrköping, Piteå, Skellefteå, Skövde, Staffanstorp, Bromma, Sundsvall, Umeå, Uppsala, Växjö, Västerås, Ängelholm, Örnsköldsvik, Örebro",
    "Number of employees": "In sweden 2.S300 and global over 8.0000",
    "SustainabilityWork": "Our biggest contribution is that we work towards a paperless society by reducing traditional paper handling and invoicing to become a cloud-based society.\n\n Sustainability is on of Vismas focus areas for 2019.",
    "Interested in": "Computer Science / InfoCom",
    "Offer": "Summer job, Master thesis, Full Time Employment, Management Trainee program",
    "Name of contact person": "Kajza Zellman Sjööblom",
    "Email of contact person": "kajza.zellman@visma.com",
    "": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/visma.png")
  },
  {
    "key": 59,
    "Company": "Volvo Car Corporation",
    "AboutCompany": "Volvo Cars is a company on a mission; to bring traditional car manufacturing into a connected, sustainable and smart future.\nWe are a brand known for our commitment to safety, creating innovative cars that make life less complicated for people. We are looking for innovative, committed people to create safe, sustainable and connected cars.\nJoin us and be part of Volvo Cars’ journey into the future!",
    "OfficeLocation": "Lund, Copenhagen, Göteborg, Stockholm",
    "Number of employees": "In Sweden 30.000 and Global 43.000",
    "SustainabilityWork": "As a human-centric car company, we are a brand for people who care about other people and the world in which we live. \nThis is at the core of our business and of our approach to sustainability...\nRead more: https://group.volvocars.com/sustainability",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Full Time Employment",
    "Name of contact person": "",
    "Email of contact person": "",
    "": "",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/volvo.png")
  }
]
export default companyData