const companyData = [
  {
    "key": 1,
    "Company": "Bosch",
    "In the company info on website and app, do you want to show the email of your contact person?": "Yes",
    "Do you want to use same contact-info as we have for your Teknikfokus-application?": "No (You will add in next section)",
    "Have you uploaded the logo?": "Yes",
    "About your company": "The Lund office is a development site working on software solutions for connecting Bosch devices to the internet in a secure way. Main focus is automotive devices to connect vehicles, but also on CE-devices like the next generation eBike-computer.",
    "Where do you have offices?": "Lund m.m",
    "Number of employees": 250,
    "In what way does your company work for  Sustainability?": "Environment, society, sustainable innovation, climate-friendly production",
    "Interested in": "Computer Science / InfoCom, Electrical Engineering",
    "Offer": "Summer job, Extra job, Master thesis",
    "Name of contact person": "Nils Nilsson",
    "Email of contact person": "nils@hej.se",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/logo.png")
  },
  {
    "key": 2,
    "Company": "Venture Cup",
    "In the company info on website and app, do you want to show the email of your contact person?": "Yes",
    "Do you want to use same contact-info as we have for your Teknikfokus-application?": "Yes",
    "Have you uploaded the logo?": "Yes",
    "About your company": "Venture Cup have supported tens of thousands of entrepreneurs and helped nearly 15 000 ideas to blossom since the start in 1998. We are Sweden's no. 1 competition and the competition where ideas become businesses. Each year we arrange two competitions, IDEA and STARTUP. The spring is all about startups in an early phase, and during the fall the competition is all about ideas. By challenging yourself, meet our network and get feedback on the business idea, both the entrepreneur and the business idea develops during the competition process.",
    "Where do you have offices?": "Lund, G�teborg, Stockholm, Ume� and Lule�",
    "Number of employees": 11,
    "In what way does your company work for  Sustainability?": "Venture Cups purpose is to connect people with ideas to experts and the crowd, to ignite the creation of new businesses and empower the growth of Sweden.",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "To compete in our competitions",
    "Name of contact person": "",
    "Email of contact person": "",
    "Day": "12 February",
    "Logo-fileName": require("./companieImg/ventureCup.png")
  },
  {
    "key": 3,
    "Company": "Tetra Pak",
    "In the company info on website and app, do you want to show the email of your contact person?": "No",
    "Do you want to use same contact-info as we have for your Teknikfokus-application?": "No (You will add in next section)",
    "Have you uploaded the logo?": "Yes",
    "About your company": "Tetra Pak is the world's leading food processing and packaging solutions company. Working closely with our customers and suppliers, we provide safe, innovative and environmentally sound products that each day meet the needs of hundreds of millions of people in more than 160 countries. With more than 24,000 employees around the world, we believe in responsible industry leadership and a sustainable approach to business.  Our motto, %u201CPROTECTS WHAT%u2019S GOOD%u2122,\" reflects our vision to make food safe and available, everywhere.%u200B%u200B",
    "Where do you have offices?": "Lund",
    "Number of employees": "In Sweden 3 700 and global 24 800",
    "In what way does your company work for  Sustainability?": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Trainee programs",
    "Name of contact person": "",
    "Email of contact person": "",
    "Day": "First day of the fair, 12 February",
    "Logo-fileName": require("./companieImg/TetraPak.png")
  },
  {
    "key": 4,
    "Company": "aPak",
    "In the company info on website and app, do you want to show the email of your contact person?": "No",
    "Do you want to use same contact-info as we have for your Teknikfokus-application?": "No (You will add in next section)",
    "Have you uploaded the logo?": "Yes",
    "About your company": "Tetra Pak is the world's leading food processing and packaging solutions company. Working closely with our customers and suppliers, we provide safe, innovative and environmentally sound products that each day meet the needs of hundreds of millions of people in more than 160 countries. With more than 24,000 employees around the world, we believe in responsible industry leadership and a sustainable approach to business.  Our motto, %u201CPROTECTS WHAT%u2019S GOOD%u2122,\" reflects our vision to make food safe and available, everywhere.%u200B%u200B",
    "Where do you have offices?": "Lund",
    "Number of employees": "In Sweden 3 700 and global 24 800",
    "In what way does your company work for  Sustainability?": "",
    "Interested in": "Computer Science / InfoCom, Biomedical Engineering, Electrical Engineering",
    "Offer": "Summer job, Master thesis, Trainee programs",
    "Name of contact person": "Olle Blomm",
    "Email of contact person": "dgfsghgsh@libe.com",
    "Day": "13 February",
    "Logo-fileName": require("./companieImg/CDON.png")
  }
]
export default companyData